// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjdMWbSaz9zphvdYAGfEyQSS2N8OkWqBU',
    appId: '1:893512786165:web:a6610cbd7128a13c83a5bc',
    messagingSenderId: '893512786165',
    projectId: 'stylish-579e9',
    authDomain: 'stylish-579e9.firebaseapp.com',
    storageBucket: 'stylish-579e9.firebasestorage.app',
    measurementId: 'G-T2JRPYVM63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpcNsXpCyYPtiu4H9EnQCi_5WTBHFq7o',
    appId: '1:893512786165:android:11ec2cd8ba4e1c9183a5bc',
    messagingSenderId: '893512786165',
    projectId: 'stylish-579e9',
    storageBucket: 'stylish-579e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PLE2EllCWIbx0f9ht5MmgYer2vxsKAY',
    appId: '1:893512786165:ios:40fc19cbe466d85083a5bc',
    messagingSenderId: '893512786165',
    projectId: 'stylish-579e9',
    storageBucket: 'stylish-579e9.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PLE2EllCWIbx0f9ht5MmgYer2vxsKAY',
    appId: '1:893512786165:ios:40fc19cbe466d85083a5bc',
    messagingSenderId: '893512786165',
    projectId: 'stylish-579e9',
    storageBucket: 'stylish-579e9.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );
}
